POST {{baseURL}}character
Content-Type: application/json

{
  "name": "Raiva",
  "level": 50,
  "className": "Spiritmaster",
  "chest": "soul-scarred vest",
  "jewel": "sulphurous fiend gem",
  "twoHanded": "tenacious night shadow",
  "helm": "cloth cap",
  "belt": "belt of consumed souls",
  "cloak": "cape of legerdemain",
  "mythirian": "dragon intellect mythirian",
  "necklace": "midgard medal of honor",
  "lBracer": "arcane-infused armband",
  "rBracer": "arcane shadow cuff",
  "lRing": "tock",
  "rRing": "ring of the vaettir",
  "boots": "aidon's slippers"
}